---
abstract: "It's new $module"
author:
  - 'Mike Ryan <falter at gmail.com>'
build_requires:
  Test::Class: 0.41
  Test::Exception: 0.32
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cikl
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Cikl:
    file: lib/Cikl.pm
    version: 0.04
  Cikl::AddressBuilder:
    file: lib/Cikl/AddressBuilder.pm
  Cikl::Authentication::Factory:
    file: lib/Cikl/Authentication/Factory.pm
  Cikl::Authentication::Role:
    file: lib/Cikl/Authentication/Role.pm
  Cikl::Client:
    file: lib/Cikl/Client.pm
  Cikl::Client::Factory:
    file: lib/Cikl/Client/Factory.pm
  Cikl::Client::Transport:
    file: lib/Cikl/Client/Transport.pm
  Cikl::Client::Transport::RabbitMQ:
    file: lib/Cikl/Client/Transport/RabbitMQ.pm
  Cikl::Codecs::CodecRole:
    file: lib/Cikl/Codecs/CodecRole.pm
  Cikl::Codecs::JSON:
    file: lib/Cikl/Codecs/JSON.pm
  Cikl::Common::RabbitMQRole:
    file: lib/Cikl/Common/RabbitMQRole.pm
  Cikl::DataStore::Factory:
    file: lib/Cikl/DataStore/Factory.pm
  Cikl::DataStore::Role:
    file: lib/Cikl/DataStore/Role.pm
  Cikl::DataTypes::Asn:
    file: lib/Cikl/DataTypes/Asn.pm
  Cikl::DataTypes::Email:
    file: lib/Cikl/DataTypes/Email.pm
  Cikl::DataTypes::Fqdn:
    file: lib/Cikl/DataTypes/Fqdn.pm
  Cikl::DataTypes::Integer:
    file: lib/Cikl/DataTypes/Integer.pm
  Cikl::DataTypes::Ipv4:
    file: lib/Cikl/DataTypes/Ipv4.pm
  Cikl::DataTypes::Ipv4Cidr:
    file: lib/Cikl/DataTypes/Ipv4Cidr.pm
  Cikl::DataTypes::LowerCaseStr:
    file: lib/Cikl/DataTypes/LowerCaseStr.pm
  Cikl::DataTypes::LowercaseUUID:
    file: lib/Cikl/DataTypes/LowercaseUUID.pm
  Cikl::DataTypes::PortList:
    file: lib/Cikl/DataTypes/PortList.pm
  Cikl::DataTypes::Url:
    file: lib/Cikl/DataTypes/Url.pm
  Cikl::EventBuilder:
    file: lib/Cikl/EventBuilder.pm
  Cikl::Models::Address::asn:
    file: lib/Cikl/Models/Address/asn.pm
  Cikl::Models::Address::email:
    file: lib/Cikl/Models/Address/email.pm
  Cikl::Models::Address::fqdn:
    file: lib/Cikl/Models/Address/fqdn.pm
  Cikl::Models::Address::ipv4:
    file: lib/Cikl/Models/Address/ipv4.pm
  Cikl::Models::Address::ipv4_cidr:
    file: lib/Cikl/Models/Address/ipv4_cidr.pm
  Cikl::Models::Address::url:
    file: lib/Cikl/Models/Address/url.pm
  Cikl::Models::AddressRole:
    file: lib/Cikl/Models/AddressRole.pm
  Cikl::Models::Event:
    file: lib/Cikl/Models/Event.pm
  Cikl::Models::HostInfo:
    file: lib/Cikl/Models/HostInfo.pm
  Cikl::Models::Query:
    file: lib/Cikl/Models/Query.pm
  Cikl::Models::QueryAddress:
    file: lib/Cikl/Models/QueryAddress.pm
  Cikl::Models::QueryRange:
    file: lib/Cikl/Models/QueryRange.pm
  Cikl::Models::QueryResults:
    file: lib/Cikl/Models/QueryResults.pm
  Cikl::Models::Submission:
    file: lib/Cikl/Models/Submission.pm
  Cikl::QueryHandler::Factory:
    file: lib/Cikl/QueryHandler/Factory.pm
  Cikl::QueryHandler::Role:
    file: lib/Cikl/QueryHandler/Role.pm
  Cikl::Report::CSVFormatter:
    file: lib/Cikl/Report/CSVFormatter.pm
  Cikl::Report::Formatter:
    file: lib/Cikl/Report/Formatter.pm
  Cikl::Report::Output:
    file: lib/Cikl/Report/Output.pm
  Cikl::Report::QueryResultsReport:
    file: lib/Cikl/Report/QueryResultsReport.pm
  Cikl::Report::ReportInterface:
    file: lib/Cikl/Report/ReportInterface.pm
  Cikl::Report::TableFormatter:
    file: lib/Cikl/Report/TableFormatter.pm
  Cikl::Router::AuthenticatedRole:
    file: lib/Cikl/Router/AuthenticatedRole.pm
  Cikl::Router::Constants:
    file: lib/Cikl/Router/Constants.pm
  Cikl::Router::DataSubmissionRole:
    file: lib/Cikl/Router/DataSubmissionRole.pm
  Cikl::Router::QueryHandlingRole:
    file: lib/Cikl/Router/QueryHandlingRole.pm
  Cikl::Router::Server:
    file: lib/Cikl/Router/Server.pm
  Cikl::Router::ServerFactory:
    file: lib/Cikl/Router/ServerFactory.pm
  Cikl::Router::ServiceRole:
    file: lib/Cikl/Router/ServiceRole.pm
  Cikl::Router::Services:
    file: lib/Cikl/Router/Services.pm
  Cikl::Router::Services::Control:
    file: lib/Cikl/Router/Services/Control.pm
  Cikl::Router::Services::Query:
    file: lib/Cikl/Router/Services/Query.pm
  Cikl::Router::Services::Submission:
    file: lib/Cikl/Router/Services/Submission.pm
  Cikl::Router::Transport:
    file: lib/Cikl/Router/Transport.pm
  Cikl::Router::Transport::RabbitMQ:
    file: lib/Cikl/Router/Transport/RabbitMQ.pm
  Cikl::Router::Transport::RabbitMQ::Consumer:
    file: lib/Cikl/Router/Transport/RabbitMQ/Consumer.pm
  Cikl::Router::Transport::RabbitMQ::DeferredAcker:
    file: lib/Cikl/Router/Transport/RabbitMQ/DeferredAcker.pm
  Cikl::Router::Transport::RabbitMQ::SubmissionConsumer:
    file: lib/Cikl/Router/Transport/RabbitMQ/SubmissionConsumer.pm
  Cikl::Smrt:
    file: lib/Cikl/Smrt.pm
    version: 0.04
  Cikl::Smrt::AutoDecodableRole:
    file: lib/Cikl/Smrt/AutoDecodableRole.pm
  Cikl::Smrt::Broker:
    file: lib/Cikl/Smrt/Broker.pm
  Cikl::Smrt::ClientBroker:
    file: lib/Cikl/Smrt/ClientBroker.pm
  Cikl::Smrt::DecoderRole:
    file: lib/Cikl/Smrt/DecoderRole.pm
  Cikl::Smrt::Decoders::AutoDecoder:
    file: lib/Cikl/Smrt/Decoders/AutoDecoder.pm
  Cikl::Smrt::Decoders::Gzip:
    file: lib/Cikl/Smrt/Decoders/Gzip.pm
  Cikl::Smrt::Decoders::Null:
    file: lib/Cikl/Smrt/Decoders/Null.pm
  Cikl::Smrt::Decoders::Zip:
    file: lib/Cikl/Smrt/Decoders/Zip.pm
  Cikl::Smrt::FeedParserConfig:
    file: lib/Cikl/Smrt/FeedParserConfig.pm
  Cikl::Smrt::Fetcher:
    file: lib/Cikl/Smrt/Fetcher.pm
  Cikl::Smrt::Fetchers:
    file: lib/Cikl/Smrt/Fetchers.pm
  Cikl::Smrt::Fetchers::File:
    file: lib/Cikl/Smrt/Fetchers/File.pm
  Cikl::Smrt::Fetchers::Http:
    file: lib/Cikl/Smrt/Fetchers/Http.pm
  Cikl::Smrt::HandlerRole:
    file: lib/Cikl/Smrt/HandlerRole.pm
  Cikl::Smrt::Handlers::Alexa:
    file: lib/Cikl/Smrt/Handlers/Alexa.pm
  Cikl::Smrt::Handlers::ConfigBasedHandler:
    file: lib/Cikl/Smrt/Handlers/ConfigBasedHandler.pm
  Cikl::Smrt::Parser:
    file: lib/Cikl/Smrt/Parser.pm
  Cikl::Smrt::ParserHelpers::XPathMapping:
    file: lib/Cikl/Smrt/ParserHelpers/XPathMapping.pm
  Cikl::Smrt::ParserHelpers::XPathRegexMapping:
    file: lib/Cikl/Smrt/ParserHelpers/XPathRegexMapping.pm
  Cikl::Smrt::Parsers:
    file: lib/Cikl/Smrt/Parsers.pm
  Cikl::Smrt::Parsers::ParseCsv:
    file: lib/Cikl/Smrt/Parsers/ParseCsv.pm
  Cikl::Smrt::Parsers::ParseDelim:
    file: lib/Cikl/Smrt/Parsers/ParseDelim.pm
  Cikl::Smrt::Parsers::ParseJson:
    file: lib/Cikl/Smrt/Parsers/ParseJson.pm
  Cikl::Smrt::Parsers::ParseTxt:
    file: lib/Cikl/Smrt/Parsers/ParseTxt.pm
  Cikl::Smrt::Parsers::ParseXPath:
    file: lib/Cikl/Smrt/Parsers/ParseXPath.pm
  Cikl::Util::Flushable:
    file: lib/Cikl/Util/Flushable.pm
  Cikl::Util::Flusher:
    file: lib/Cikl/Util/Flusher.pm
  Cikl::Util::TimeHelpers:
    file: lib/Cikl/Util/TimeHelpers.pm
requires:
  AnyEvent: 7.05
  AnyEvent::RabbitMQ: 1.15
  Config::Simple: 4.58
  Coro: 6.31
  Cwd: 3.40
  DateTime: 0.70
  DateTime::Format::DateParse: 0.05
  DateTime::Format::Strptime: 1.54
  Digest::MD5: 2.51
  Digest::SHA: 5.70
  Encode: 2.44
  File::Spec: 3.40
  File::Type: 0.22
  Getopt::Long: 0
  IO::Uncompress::Unzip: 2.02
  JSON::XS: 2.34
  LWP::Protocol::https: 6.03
  LWP::UserAgent: 6.02
  LWPx::ParanoidAgent: 1.09
  List::MoreUtils: 0.33
  Log::Dispatch: 2.32
  MIME::Base64: 3.13
  MIME::Lite: 3.027
  Mail::RFC822::Address: 0.3
  Module::Pluggable: 3.9
  Mouse: v2.0.0
  Net::RabbitFoot: 1.03
  Net::SSLeay: 1.43
  Regexp::Common: 2.122
  Regexp::Common::net::CIDR: 0.02
  Storable: 2.27
  Text::CSV_XS: 1.00
  Text::Table: 1.127
  Time::HiRes: 1.972101
  Try::Tiny: 0.11
  UUID::Tiny: 1.04
  XML::LibXML: 1.89
  perl: 5.014
resources:
  bugtracker: https://github.com/cikl/p5-Cikl/issues
  homepage: https://github.com/cikl/p5-Cikl
  repository: git://github.com/cikl/p5-Cikl.git
version: 0.04
x_contributors:
  - 'Kevin Benton <blak111@gmail.com>'
  - 'Aaron K. Reffett <akreffett@cert.org>'
  - 'Matt Carothers <macaroth@t5.sie.isc.org>'
  - 'Wes Young <github@barely3am.com>'
  - 'Gabriel Iovino <giovino@gmail.com>'
  - 'Wes Young <wes@barely3am.com>'
  - 'Mike Ryan <falter@gmail.com>'
